### ISSUE TITLE
有关报错

### ISSUE THREAD

**Issue by XTxiaoting14332** [AkashiCoin/nonebot-plugin-chatgpt-plus#17]
昨晚使用时提示了“API错误 请联系开发者”
今天再次尝试请求时抛出了“ValueError: Tag "<html>" does not correspond to any known ansi directive, make sure you did not misspelled it (or prepend '\' to escape it)”
已经更新至最新版本，报错如下：
<code>04-16 01:08:55 [ERROR] nonebot_plugin_chatgpt_plus | ChatGPT request failed: ValueError: Tag "<html>" does not correspond to any known ansi directive, make sure you did not misspelled it (or prepend '\' to escape it)
Traceback (most recent call last):
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot_plugin_chatgpt_plus/chatgpt.py", line 281, in refresh_session
    self.authorization = response.json()["accessToken"]
  File "/home/NightWind/.venv/lib/python3.8/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/home/NightWind/.venv/lib/python3.8/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/home/NightWind/.venv/lib/python3.8/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
    await handler(
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot_plugin_chatgpt_plus/__init__.py", line 125, in ai_chat
    msg = await chat_bot(**cvst, played_name=played_name).get_chat_response(text)
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot_plugin_chatgpt_plus/chatgpt.py", line 131, in get_chat_response
    await self.refresh_session()
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot_plugin_chatgpt_plus/chatgpt.py", line 283, in refresh_session
    logger.opt(colors=True, exception=e).error(
  File "/home/NightWind/.venv/lib/python3.8/site-packages/loguru/_colorizer.py", line 369, in prepare_simple_message
    parser.feed(string)
  File "/home/NightWind/.venv/lib/python3.8/site-packages/loguru/_colorizer.py", line 253, in feed
    raise ValueError(
ValueError: Tag "<html>" does not correspond to any known ansi directive, make sure you did not misspelled it (or prepend '\' to escape it)</code>

**Comment by XTxiaoting14332** [comment]
<code>04-16 01:08:55 [ERROR] nonebot_plugin_chatgpt_plus | ChatGPT request failed: ValueError: Tag "<html>" does not correspond to any known ansi directive, make sure you did not misspelled it (or prepend '\' to escape it)
Traceback (most recent call last):
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot_plugin_chatgpt_plus/chatgpt.py", line 281, in refresh_session
    self.authorization = response.json()["accessToken"]
  File "/home/NightWind/.venv/lib/python3.8/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/home/NightWind/.venv/lib/python3.8/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/home/NightWind/.venv/lib/python3.8/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
    await handler(
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot_plugin_chatgpt_plus/__init__.py", line 125, in ai_chat
    msg = await chat_bot(**cvst, played_name=played_name).get_chat_response(text)
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot_plugin_chatgpt_plus/chatgpt.py", line 131, in get_chat_response
    await self.refresh_session()
  File "/home/NightWind/.venv/lib/python3.8/site-packages/nonebot_plugin_chatgpt_plus/chatgpt.py", line 283, in refresh_session
    logger.opt(colors=True, exception=e).error(
  File "/home/NightWind/.venv/lib/python3.8/site-packages/loguru/_colorizer.py", line 369, in prepare_simple_message
    parser.feed(string)
  File "/home/NightWind/.venv/lib/python3.8/site-packages/loguru/_colorizer.py", line 253, in feed
    raise ValueError(
ValueError: Tag "<html>" does not correspond to any known ansi directive, make sure you did not misspelled it (or prepend '\' to escape it)</code>

**Comment by AkashiCoin** [comment]
api已修复，稳定性待测试
