### ISSUE TITLE
i have e error 'ChatGPT request failed: ResponseNotRead: Attempted to access streaming response content, without having called `read()`'

### ISSUE THREAD

**Issue by DuanShaoCheng** [AkashiCoin/nonebot-plugin-chatgpt-plus#18]
Traceback (most recent call last):
  File "/root/MyBot/bot.py", line 41, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/root/MyBot/.venv/lib/python3.9/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/root/MyBot/.venv/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/root/MyBot/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/root/MyBot/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/MyBot/.venv/lib/python3.9/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "/root/MyBot/.venv/lib/python3.9/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/MyBot/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/MyBot/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
    await handler(
  File "/root/MyBot/.venv/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "/root/MyBot/.venv/lib/python3.9/site-packages/nonebot_plugin_chatgpt_plus/__init__.py", line 125, in ai_chat
    msg = await chat_bot(**cvst, played_name=played_name).get_chat_response(text)
  File "/root/MyBot/.venv/lib/python3.9/site-packages/nonebot_plugin_chatgpt_plus/chatgpt.py", line 155, in get_chat_response
    f"非预期的响应内容: <r>HTTP{response.status_code}</r> {escape_tag(response.text)}"
  File "/root/MyBot/.venv/lib/python3.9/site-packages/httpx/_models.py", line 574, in text
    content = self.content
  File "/root/MyBot/.venv/lib/python3.9/site-packages/httpx/_models.py", line 568, in content
    raise ResponseNotRead()
httpx.ResponseNotRead: Attempted to access streaming response content, without having called `read()`.

之前一直没有问题，今天出现的

**Comment by AkashiCoin** [comment]
api已修复，稳定性待测试
