### ISSUE TITLE
  from OpenAIAuth.OpenAIAuth import OpenAIAuth

### ISSUE THREAD

**Issue by canxin121** [AkashiCoin/nonebot-plugin-chatgpt-plus#2]
04-03 04:57:16 [ERROR] nonebot_plugin_chatgpt_plus | ChatGPT request failed: ModuleNotFoundError: No module named 'OpenAIAuth.OpenAIAuth'; 'OpenAIAuth' is not a package
Traceback (most recent call last):
  File "/bot/cxbot/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "/bot/cxbot/.venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt_plus/__init__.py", line 117, in ai_chat
    msg = await chat_bot(**cvst, played_name=played_name).get_chat_response(text)
  File "/bot/cxbot/.venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt_plus/chatgpt.py", line 128, in get_chat_response
    await self.refresh_session()
  File "/bot/cxbot/.venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt_plus/chatgpt.py", line 232, in refresh_session
    await self.login()
  File "/bot/cxbot/.venv/lib/python3.10/site-packages/nonebot/utils.py", line 113, in _wrapper
    result = await loop.run_in_executor(None, pfunc)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/bot/cxbot/.venv/lib/python3.10/site-packages/nonebot_plugin_chatgpt_plus/chatgpt.py", line 288, in login
    from OpenAIAuth.OpenAIAuth import OpenAIAuth
ModuleNotFoundError: No module named 'OpenAIAuth.OpenAIAuth'; 'OpenAIAuth' is not a package
看不懂这个import怎么重复三次OpenAIAuth

**Comment by AkashiCoin** [comment]
版本残留，现无法使用，等下去删了，换一个
