### ISSUE TITLE
token失效，请重新设置token

### ISSUE THREAD

**Issue by DuanShaoCheng** [AkashiCoin/nonebot-plugin-chatgpt-plus#21]
更新了 0.8.5 它提示 token失效，请重新设置token ，并且后台出现报错应该与token失效有关
Traceback (most recent call last):
  File "/root/JinCheng/JinChengBot/bot.py", line 42, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/root/JinCheng/.venv/lib64/python3.11/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/root/JinCheng/.venv/lib64/python3.11/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/root/JinCheng/.venv/lib64/python3.11/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/root/JinCheng/.venv/lib64/python3.11/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/root/JinCheng/.venv/lib64/python3.11/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/JinCheng/.venv/lib64/python3.11/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/JinCheng/.venv/lib64/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/JinCheng/.venv/lib64/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
    await handler(
  File "/root/JinCheng/.venv/lib64/python3.11/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/JinCheng/.venv/lib64/python3.11/site-packages/nonebot_plugin_chatgpt_plus/__init__.py", line 159, in ai_chat
    await chat_bot(**session[event]).edit_title(session.id(event=event))
  File "/root/JinCheng/.venv/lib64/python3.11/site-packages/nonebot_plugin_chatgpt_plus/chatgpt.py", line 196, in edit_title
    urljoin(self.api_url, "backend-api/conversation/" + self.conversation_id),
TypeError: can only concatenate str (not "NoneType") to str
我的token没有失效都是现获取的

**Comment by DuanShaoCheng** [comment]
新修复的版本是否可以不使用token使用账户密码登录？

**Comment by AkashiCoin** [comment]
检查setting.json文件，这个文件会有缓存token，你应该将这个文件删除后，做出的环境变量的修改才会生效

**Comment by DuanShaoCheng** [comment]
感谢大佬解惑~~~ 现在终于能用了

> 检查setting.json文件，这个文件会有缓存token，你应该将这个文件删除后，做出的环境变量的修改才会生效 有关账号密码登录，正在修复
