### ISSUE TITLE
KeyError: 'error'

### ISSUE THREAD

**Issue by Enceladus6** [AkashiCoin/nonebot-plugin-chatgpt-plus#41]
请求 ChatGPT 服务器时出现问题，请稍后再试
错误信息: KeyError: 'error'
昨天晚上运行正常，今天早上突然报了这个错误，不知道如何解决

```
07-20 12:41:30 [ERROR] nonebot_plugin_chatgpt_plus | ChatGPT request failed: KeyError: 'error'
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "D:\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "D:\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "D:\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
  File "D:\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "D:\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "D:\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\nonebot_plugin_chatgpt_plus\__init__.py", line 133, in ai_chat
    msg = await chat_bot(
  File "D:\Bot\Nonebot2\GPT-Qbot\GPT-Qbot\.venv\Lib\site-packages\nonebot_plugin_chatgpt_plus\chatgpt.py", line 208, in get_chat_response
    while data_list[idx]["error"]:
KeyError: 'error'

```

**Comment by Karmau-Git** [comment]
我也是 上午还可以下午不行了 尝试更换了token依旧报错

**Comment by Enceladus6** [comment]
看了下chatgpt网页，里面是可以收到信息的，也返回了回答，只是没办法被bot转发到qq

**Comment by Leonado-LEO** [comment]
是第三方的api出问题了吗？我今天也遇到这个情况了

**Comment by CGH0S7** [comment]
请问现在有解决办法了吗

**Comment by Leonado-LEO** [comment]
我正在使用nonebot-plugin-talk-with-chatgpt代替。
[https://github.com/nikissXI/nonebot_plugins/tree/main/nonebot_plugin_talk_with_chatgpt](url)

**Comment by Loss-of-time** [comment]
现在有解决办法了吗

**Comment by 2055135** [comment]
> 现在有解决办法了吗

额，我好像把他修好了

**Comment by 2055135** [comment]
但还没完全好

**Comment by 2055135** [comment]
[nonebot_plugin_chatgpt_plus.zip](https://github.com/AkashiCoin/nonebot-plugin-chatgpt-plus/files/12183526/nonebot_plugin_chatgpt_plus.zip)


> 现在有解决办法了吗

这是我尝试修的插件，目前无法使用预设，设置了也用不了

**Comment by Loss-of-time** [comment]
为什么不fork一下呢

**Comment by 2055135** [comment]
改动后的链接
https://github.com/2055135/nonebot-plugin-chatgpt-plus/tree/2055135-patch-1
