### ISSUE TITLE
DLL load failed while importing ujson: 找不到指定的模块。

### ISSUE THREAD

**Issue by Enceladus6** [AkashiCoin/nonebot-plugin-chatgpt-plus#44]
在云服务器部署时出现错误：DLL load failed while importing ujson: 找不到指定的模块。
```
08-14 14:14:08 [ERROR] nonebot | Failed to import "nonebot_plugin_chatgpt_plus"
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot_plugin_chatgpt_plus\__init__.py", line 16, in <module>
    from .chatgpt import Chatbot
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot_plugin_chatgpt_plus\chatgpt.py", line 11, in <module>
    from .utils import convert_seconds
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot_plugin_chatgpt_plus\utils.py", line 24, in <module>
    from .data import setting
  File "C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot_plugin_chatgpt_plus\data.py", line 9, in <module>
    import ujson as json
ImportError: DLL load failed while importing ujson: 找不到指定的模块。
```

**Comment by AkashiCoin** [comment]
可以把`nonebot_plugin_chatgpt_plus/data.py`(根据你的错误信息，其在`C:\Users\Administrator\Desktop\Cloud\.venv\lib\site-packages\nonebot_plugin_chatgpt_plus\data.py`)的8-11行的
```
try:
    import ujson as json
except ModuleNotFoundError:
    import json
```
改成
```
import json
```

**Comment by Enceladus6** [comment]
好的，非常感谢
